# Generated by Django 5.0.7 on 2025-10-14 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adver', '0001_initial'),
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Trip Day',
                'verbose_name_plural': 'Trip Days',
                'ordering': ['trip_plan', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('location', 'Location Visit'), ('travel', 'Travel'), ('break', 'Break'), ('accommodation', 'Accommodation')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('ad_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adver.adlocation')),
                ('gi_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.gilocation')),
                ('trip_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='itinerary.tripday')),
            ],
            options={
                'verbose_name': 'Schedule Item',
                'verbose_name_plural': 'Schedule Items',
                'ordering': ['trip_day', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_location_name', models.CharField(max_length=255)),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('num_days', models.IntegerField(default=1)),
                ('available_hours_per_day', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Plan',
                'verbose_name_plural': 'Trip Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tripday',
            name='trip_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_days', to='itinerary.tripplan'),
        ),
        migrations.CreateModel(
            name='SelectedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('ad_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adver.adlocation')),
                ('gi_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.gilocation')),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_locations', to='itinerary.tripplan')),
            ],
            options={
                'verbose_name': 'Selected Location',
                'verbose_name_plural': 'Selected Locations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tripday',
            unique_together={('trip_plan', 'day_number')},
        ),
    ]
