# Generated by Django 5.0.7 on 2025-10-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gilocation',
            name='sellable_quantity',
            field=models.IntegerField(blank=True, help_text='Available quantity for sale (optional, leave empty if not sellable)', null=True),
        ),
    ]
